import nltk
import pandas as pd
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Download VADER lexicon for sentiment analysis (only first time)
nltk.download('vader_lexicon')

# Load the dataset
df = pd.read_csv("clean_reviews.csv")

# Initialize VADER sentiment analyzer
sia = SentimentIntensityAnalyzer()

# Function to analyze sentiment using VADER
def analyze_sentiment(text):
    score = sia.polarity_scores(str(text))["compound"]
    if score >= 0.05:
        label = "Positive"
    elif score <= -0.05:
        label = "Negative"
    else:
        label = "Neutral"
    return score, label

# Placeholder for future LLM API integration (currently uses VADER)
def analyze_sentiment_llm(text):
    return analyze_sentiment(text)

# Placeholder column for topic modeling (to be generated by LLM later)
df["topics"] = "To be generated by LLM"

# Apply sentiment analysis to first 5 reviews for demo
df_sample = df.head(5)
df_sample[["sentiment_score", "sentiment_label"]] = df_sample["review"].apply(
    lambda x: pd.Series(analyze_sentiment_llm(x))
)

# Print the first 5 reviews with sentiment scores and labels
for index, row in df_sample.iterrows():
    print(f"Review {index+1}:")
    print(f"Text: {row['review'][:100]}...")  # Show only first 100 characters
    print(f"Sentiment Score: {row['sentiment_score']}")
    print(f"Sentiment Label: {row['sentiment_label']}")
    print(f"Topics: {row['topics']}")
    print("-" * 50)

# Save the sample with sentiment scores and placeholder topics to a CSV
df_sample.to_csv("reviews_with_sentiment.csv", index=False)